#!/usr/bin/env node
import { readFileSync } from "node:fs";
import { Command } from "commander";
import { compileTask } from "./compiler.js";
import { inspectGitHub } from "./github-inspector.js";
import { reasonAboutTask } from "./ai-reasoner.js";
import { simulateTask } from "./simulator.js";
import { validateTask } from "./validator.js";
import { buildPublishPreview, publishTask } from "./gibwork.js";
import type { SimulationResult, TaskContract } from "./types.js";

const program = new Command();
program.name("gibwork").description("Compile, reason, simulate, validate, and publish precise Gibwork tasks").version("0.6.0");
function loadContract(file: string): TaskContract { return JSON.parse(readFileSync(file, "utf8")) as TaskContract; }
function loadSimulation(file: string): SimulationResult { return JSON.parse(readFileSync(file, "utf8")) as SimulationResult; }

program.command("compile").description("Compile a developer request into a structured Gibwork Task Contract").requiredOption("--request <request>", "rough task, issue, or developer request").option("--reference <reference>", "GitHub repository or issue URL").option("--currency <currency>", "reward currency", "USDC").option("--json", "output the Task Contract as JSON").action((options) => {
  try { const contract = compileTask({ request: options.request, reference: options.reference, currency: options.currency }); if (options.json) return console.log(JSON.stringify(contract, null, 2)); console.log(`\n🧩 GIBWORK TASK COMPILER\n\nOBJECTIVE\n${contract.objective}\n\nREQUIREMENTS\n${contract.requirements.map((x) => `✓ ${x}`).join("\n")}\n\nACCEPTANCE CRITERIA\n${contract.acceptanceCriteria.map((x) => `✓ ${x}`).join("\n")}\n\nRECOMMENDED REWARD\n${contract.recommendedReward.currency} ${contract.recommendedReward.min}–${contract.recommendedReward.max}\n\nAMBIGUITY\n${contract.ambiguityScore}/100\nREADINESS\n${contract.readiness}\n`); } catch (error) { console.error(`\n✖ ${error instanceof Error ? error.message : String(error)}`); process.exitCode = 1; }
});

program.command("simulate").description("Simulate execution using real GitHub repository and source/test content").requiredOption("--contract <file>", "Task Contract JSON file").option("--reference <reference>", "GitHub repository or issue URL to inspect").option("--json", "output machine-readable JSON").option("--output <file>", "write the simulation JSON to a file").action(async (options) => {
  try { const contract = loadContract(options.contract); const reference = options.reference ?? contract.source.reference; const inspection = reference ? await inspectGitHub(reference) : undefined; const result = simulateTask(contract, inspection); const payload = JSON.stringify({ ...result, inspection }, null, 2); if (options.output) { const { writeFileSync } = await import("node:fs"); writeFileSync(options.output, payload + "\n", "utf8"); } if (options.json || options.output) return console.log(payload); console.log(`\n🧪 GIBWORK TASK SIMULATION\n\nEXECUTION PLAN\n${result.executionPlan.map((x, i) => `${i + 1}. ${x}`).join("\n")}\n\nLIKELY FILES\n${result.likelyFiles.map((x) => `• ${x}`).join("\n")}\n\nCODE EVIDENCE\n${result.codeEvidence.map((x) => `• ${x}`).join("\n") || "• None detected."}\n\nEFFORT\n${result.effort.min}–${result.effort.max}h (likely ${result.effort.likely}h)\nREWARD\n${result.reward.currency} ${result.reward.min}–${result.reward.max}\nCONFIDENCE\n${result.confidence}%\nRECOMMENDATION\n${result.recommendation}\n`); } catch (error) { console.error(`\n✖ ${error instanceof Error ? error.message : String(error)}`); process.exitCode = 1; }
});

program.command("reason").description("Use repository evidence and optional Gemini reasoning to deepen a task specification").requiredOption("--contract <file>", "Task Contract JSON file").option("--reference <reference>", "GitHub repository or issue URL").option("--simulation <file>", "previous simulation JSON file").option("--json", "output machine-readable JSON").option("--output <file>", "write reasoning JSON to a file").action(async (options) => {
  try { const contract = loadContract(options.contract); const reference = options.reference ?? contract.source.reference; const inspection = reference ? await inspectGitHub(reference) : undefined; const simulation = options.simulation ? loadSimulation(options.simulation) : (inspection ? simulateTask(contract, inspection) : undefined); const result = await reasonAboutTask(contract, inspection, simulation); const payload = JSON.stringify({ ...result, repository: inspection ? `${inspection.owner}/${inspection.repo}` : undefined }, null, 2); if (options.output) { const { writeFileSync } = await import("node:fs"); writeFileSync(options.output, payload + "\n", "utf8"); } if (options.json || options.output) return console.log(payload); console.log(`\n🧠 GIBWORK AI REASONING\n\nPROVIDER\n${result.provider} · ${result.model}\n\nSUMMARY\n${result.summary}\n\nCLARIFIED OBJECTIVE\n${result.clarifiedObjective}\n\nIMPLEMENTATION PLAN\n${result.implementationPlan.map((x, i) => `${i + 1}. ${x}`).join("\n")}\n\nACCEPTANCE CRITERIA\n${result.acceptanceCriteria.map((x) => `✓ ${x}`).join("\n")}\n\nLIKELY FILES\n${result.likelyFiles.map((x) => `• ${x}`).join("\n") || "• None identified."}\n\nLIKELY TESTS\n${result.likelyTests.map((x) => `• ${x}`).join("\n") || "• None identified."}\n\nRISKS\n${result.risks.map((x) => `• ${x}`).join("\n") || "• None identified."}\n\nMISSING INFORMATION\n${result.missingInformation.map((x) => `• ${x}`).join("\n") || "• None identified."}\n\nCONFIDENCE\n${result.confidence}%\n`); } catch (error) { console.error(`\n✖ ${error instanceof Error ? error.message : String(error)}`); process.exitCode = 1; }
});

program.command("validate").description("Validate a Task Contract against acceptance criteria and optional simulation/repository evidence").requiredOption("--contract <file>", "Task Contract JSON file").option("--reference <reference>", "GitHub repository or issue URL to inspect").option("--simulation <file>", "previous simulation JSON file").option("--json", "output machine-readable JSON").action(async (options) => {
  try { const contract = loadContract(options.contract); const reference = options.reference ?? contract.source.reference; const inspection = reference ? await inspectGitHub(reference) : undefined; const simulation = options.simulation ? loadSimulation(options.simulation) : (inspection ? simulateTask(contract, inspection) : undefined); const result = validateTask(contract, inspection, simulation); if (options.json) return console.log(JSON.stringify({ ...result, inspection, simulation }, null, 2)); console.log(`\n🔎 GIBWORK TASK VALIDATION\nSCORE\n${result.score}/100\nREQUIREMENT COVERAGE\n${result.requirementCoverage.covered}/${result.requirementCoverage.total}\nTESTABILITY\n${result.testability.testable}/${result.testability.totalCriteria}\nRECOMMENDATION\n${result.recommendation}\n`); result.issues.forEach((issue) => console.log(`${issue.severity} · ${issue.code} · ${issue.message}`)); } catch (error) { console.error(`\n✖ ${error instanceof Error ? error.message : String(error)}`); process.exitCode = 1; }
});

program.command("preview").description("Preview exactly what would be sent to Gibwork").requiredOption("--contract <file>", "validated Task Contract JSON file").option("--json", "output machine-readable JSON").action((options) => {
  try { const preview = buildPublishPreview(loadContract(options.contract)); if (options.json) return console.log(JSON.stringify(preview, null, 2)); console.log(`\n📦 GIBWORK PUBLISH PREVIEW\n\nTITLE\n${preview.title}\n\nREWARD\n${preview.reward.currency} ${preview.reward.amount}\n\nDESCRIPTION\n${preview.description}\n`); } catch (error) { console.error(`\n✖ ${error instanceof Error ? error.message : String(error)}`); process.exitCode = 1; }
});

program.command("publish").description("Publish a validated Task Contract to Gibwork after explicit confirmation").requiredOption("--contract <file>", "validated Task Contract JSON file").option("--confirm", "explicitly confirm the on-chain/API publication").action(async (options) => {
  try { const contract = loadContract(options.contract); if (contract.readiness !== "READY") throw new Error(`Task is ${contract.readiness}. Only READY contracts can be published.`); const preview = buildPublishPreview(contract); console.log(`\n📦 GIBWORK PUBLISH PREVIEW\nTITLE: ${preview.title}\nREWARD: ${preview.reward.currency} ${preview.reward.amount}\nSOURCE: ${preview.sourceReference ?? "none"}\n`); if (!options.confirm) return console.log("No task was published. Review the preview and rerun with --confirm when ready."); const result = await publishTask(contract); console.log("\n✅ Gibwork task published successfully.\n" + JSON.stringify(result, null, 2)); } catch (error) { console.error(`\n✖ ${error instanceof Error ? error.message : String(error)}`); process.exitCode = 1; }
});

program.parseAsync().catch((error) => { console.error(error); process.exitCode = 1; });
